config/routes.rb
Rails.application.routes.draw do
  resources :technologies
  root to: 'meetups#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :meetups
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meetup.rb
class Meetup < ApplicationRecord
  serialize :guests, JSON

  def guests=(guests)
    super( guests.select(&:present?).map(&:strip) )
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  def new
    @technologies = Technology.all.to_a
  end

  def create
    @meetup = Meetup.new(meetup_params)
    respond_to do |format|
      if @meetup.save
        format.html{ redirect_to @meetup, notice: 'Meetup created.' }
        format.json{ head :ok }
      else
        format.html{ render :new }
        format.json{ render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def meetup_params
    params.require(:meetup).permit(:title, :description, :meeting_date, :seo, :technology, guests: [])
  end

end

app/controllers/start_controller.rb
class StartController < ApplicationController
  def index
  end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :set_technology, only: [:show, :edit, :update, :destroy]

  # GET /technologies
  def index
    @technologies = Technology.all
  end

  # GET /technologies/1
  def show
  end

  # GET /technologies/new
  def new
    @technology = Technology.new
  end

  # GET /technologies/1/edit
  def edit
  end

  # POST /technologies
  def create
    @technology = Technology.new(technology_params)

    if @technology.save
      redirect_to @technology, notice: 'Technology was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /technologies/1
  def update
    if @technology.update(technology_params)
      redirect_to @technology, notice: 'Technology was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /technologies/1
  def destroy
    @technology.destroy
    redirect_to technologies_url, notice: 'Technology was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technology
      @technology = Technology.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def technology_params
      params.require(:technology).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMeetReactJs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meetups/new.html.erb
<%= react_component('CreateNewMeetupForm', {technologies: @technologies}, {class: "container"})%>

app/views/start/index.html.erb
<h1>Start#index</h1>
<p>Find me in app/views/start/index.html.erb</p>
<!-- erb: paste this in view -->
<%= react_component("Start", { greeting: "Hello from react-rails." }) %>

<h1>From Here</h1>
<div id='start'></div>

app/views/technologies/_form.html.erb
<%= form_with(model: technology) do |form| %>
  <% if technology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(technology.errors.count, "error") %> prohibited this technology from being saved:</h2>

      <ul>
        <% technology.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/technologies/edit.html.erb
<h1>Editing Technology</h1>

<%= render 'form', technology: @technology %>

<%= link_to 'Show', @technology %> |
<%= link_to 'Back', technologies_path %>

app/views/technologies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Technologies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @technologies.each do |technology| %>
      <tr>
        <td><%= technology.name %></td>
        <td><%= link_to 'Show', technology %></td>
        <td><%= link_to 'Edit', edit_technology_path(technology) %></td>
        <td><%= link_to 'Destroy', technology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Technology', new_technology_path %>

app/views/technologies/new.html.erb
<h1>New Technology</h1>

<%= render 'form', technology: @technology %>

<%= link_to 'Back', technologies_path %>

app/views/technologies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @technology.name %>
</p>

<%= link_to 'Edit', edit_technology_path(@technology) %> |
<%= link_to 'Back', technologies_path %>